# version: 0.2

# phases:
#   build:
#     commands:
#       - echo Entered the build phase...
#       - mvn clean package
#   post_build:
#     commands:
#       - echo Build completed successfully
# artifacts:
#   files:
#     - target/cicdDemo.jar
#   discard-paths: yes
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/cicdDemo.jar
